# Generated by Django 6.0.2 on 2026-03-04 09:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tabel_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('role', models.CharField(choices=[('MENTOR', 'MENTOR'), ('STUDENT', 'STUDENT')], max_length=32)),
            ],
        ),
        migrations.AlterField(
            model_name='group',
            name='study_days',
            field=models.CharField(choices=[('Пн Ср Сб', 'Пн Ср Сб'), ('Вт Чт Вс', 'Вт Чт Вс')], max_length=32),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='data',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_group', to='tabel_app.group'),
        ),
        migrations.AlterField(
            model_name='lessonrecord',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_list', to='tabel_app.lesson'),
        ),
        migrations.AlterField(
            model_name='mentorprofile',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tabel_app.admin'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tabel_app.admin'),
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
