# Generated by Django 6.0.2 on 2026-03-10 09:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tabel_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='created_at',
            field=models.DateField(auto_now_add=True, default='2026-03-10'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='group',
            name='duration_months',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='group',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='group',
            name='study_days',
            field=models.CharField(choices=[('Пн Ср Сб', 'Пн Ср Сб'), ('Вт Чт Вс', 'Вт Чт Вс')], max_length=32),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='data',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_group', to='tabel_app.group'),
        ),
        migrations.AlterField(
            model_name='lessonrecord',
            name='grade',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name='lessonrecord',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_list', to='tabel_app.lesson'),
        ),
        migrations.CreateModel(
            name='MonthlyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField()),
                ('total_grade', models.IntegerField(default=0)),
                ('visit_count', models.IntegerField(default=0)),
                ('average_grade', models.FloatField(default=0.0)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tabel_app.group')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tabel_app.studentprofile')),
            ],
            options={
                'unique_together': {('student', 'group', 'month')},
            },
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
