# Generated by Django 6.0.2 on 2026-03-15 10:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tabel_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='data',
        ),
        migrations.AddField(
            model_name='group',
            name='created_at',
            field=models.DateField(auto_now_add=True, default='2026-03-15'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='group',
            name='duration_months',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='group',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lesson',
            name='date',
            field=models.DateField(default='2026-03-15'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lessonrecord',
            name='attendance',
            field=models.CharField(choices=[('present', 'Присутствовал'), ('late', 'Опоздал'), ('absent', 'Отсутствовал')], default='present', max_length=10),
        ),
        migrations.AddField(
            model_name='lessonrecord',
            name='late_minutes',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='group',
            name='study_days',
            field=models.CharField(choices=[('Пн Ср Сб', 'Пн Ср Сб'), ('Вт Чт Вс', 'Вт Чт Вс')], max_length=32),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='tabel_app.group'),
        ),
        migrations.AlterField(
            model_name='lessonrecord',
            name='grade',
            field=models.CharField(blank=True, max_length=3),
        ),
        migrations.AlterField(
            model_name='lessonrecord',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='tabel_app.lesson'),
        ),
        migrations.AlterField(
            model_name='mentorprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='students', to='tabel_app.group'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='lessonrecord',
            unique_together={('student', 'lesson')},
        ),
        migrations.CreateModel(
            name='MonthlyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField()),
                ('total_grade', models.IntegerField(default=0)),
                ('visit_count', models.IntegerField(default=0)),
                ('average_grade', models.FloatField(default=0.0)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tabel_app.group')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tabel_app.studentprofile')),
            ],
            options={
                'unique_together': {('student', 'group', 'month')},
            },
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
